// propertyFeatures.ts

export const propertyFeatures = [
    "Swimming Pool",
    "Garden",
    "Garage",
    "Balcony",
    "Fireplace",
    "Gym",
    "Parking",
    "Sauna",
    "Washer/Dryer",
    "Air Conditioning",
    "Dishwasher",
    "Furnished",
    "Security System",
    "Walk-in Closet",
    "Pet Friendly",
    "Elevator",
    "Smart Home",
    "Rooftop Terrace",
    "Basement",
    "Solar Panels",
    "Garden Shed",
    "Home Office",
    "Playground",
    "Bicycle Storage",
    "Security Gate",
    "Fenced Yard",
    "Wheelchair Accessible",
    "Electric Car Charging Station",
    "Jacuzzi",
    "Double Glazed Windows",
    "High Ceilings",
    "Ceiling Fans",
    "Hardwood Floors",
    "Granite Countertops",
    "Marble Floors",
    "Custom Cabinetry",
    "Home Theater",
    "Walk-in Pantry",
    "Open Floor Plan",
    "Large Windows",
    "Mudroom",
    "Recessed Lighting",
    "Central Heating",
    "Central Cooling",
    "High-Speed Internet",
    "Cable Ready",
    "Wine Cellar",
    "Hot Tub",
    "Gated Community",
    "Swimming Pool Heater",
    "Fire Pit",
    "Laundry Room",
    "Guest House",
    "Private Garden",
    "Home Gym",
    "Barbecue Area",
    "Sports Court",
    "Walkable Neighborhood",
    "Views of the City",
    "City Lights",
    "Lake View",
    "Mountain View",
    "Ocean View",
    "Backyard Patio",
    "Covered Parking",
    "Storage Shed",
    "Workshop",
    "Attic",
    "Natural Stone Counters",
    "Marble Countertops",
    "Walk-in Shower",
    "Double Vanity",
    "Security Cameras",
    "CCTV System",
    "Smart Thermostat",
    "Smart Lights",
    "Smart Locks",
    "Surround Sound System",
    "Custom Lighting",
    "Soundproofing",
    "Rain Shower",
    "Home Automation",
    "Heat Recovery Ventilation",
    "Water Filtration System",
    "Smart Refrigerator",
    "Dishwasher with Stainless Steel Finish",
    "Heated Floors",
    "Granite Island",
    "Lush Landscaping",
    "Outdoor Kitchen",
    "Wine Fridge",
    "Roof Deck",
    "Home Library",
    "Outdoor Fireplace",
    "Multi-zone HVAC",
    "Panoramic Windows",
    "Loft",
    "Garage Door Opener",
    "Wooden Blinds",
    "Skylights",
    "Built-in Speakers",
    "Pre-wired for Sound",
    "French Doors",
    "Alcove",
    "Linen Closet",
    "Mudroom Bench",
    "Open Shelving",
    "Under-cabinet Lighting",
    "Wet Bar",
    "In-wall Safe",
    "Central Vacuum System",
    "Water Softener",
    "Solar Water Heater",
    "Fireplace with Mantel",
    "Roof Solar Panels",
    "Built-in Desk",
    "Chef's Kitchen",
    "Home Office with Built-ins",
    "Double Door Entry",
    "Smart Home Hub",
    "Walk-in Closet with Organizers",
    "Marble Backsplash",
    "Backyard Swing",
    "Raised Garden Beds",
    "Shaded Patio",
    "Outdoor Shower",
    "Tile Roof",
    "Security Fence",
    "Swing Set",
    "Rainwater Collection System",
    "Garden Bench",
    "Compost Bin",
    "Storage Loft",
    "Exposed Beams",
    "Attic Storage",
    "Bamboo Flooring",
    "Cork Flooring",
    "Tile Backsplash",
    "Granite Sink",
    "Cement Flooring",
    "Storage Cupboards",
    "Custom Mantel",
    "Fireplace with Gas Logs",
    "Ceiling-to-floor Windows",
    "Centralized Sound System",
    "Outdoor Fire Pit",
    "Outdoor TV",
    "Hot Water Recirculating System",
    "Poolside Bar",
    "Solar Pool Heater",
    "Outdoor Lounge Area",
    "Heated Pool",
    "Outdoor Fan",
    "Outdoor Dining Area",
    "Shed for Tools",
    "Sprinkler System",
    "Pergola",
    "Waterfall Feature",
    "Raised Deck",
    "Pool House",
    "Zen Garden",
    "Shed for Yard Tools",
    "Home Wine Bar",
    "Fireplace in Bedroom",
    "Bar Area",
    "Master Suite with Sitting Area",
    "Smart Light Switches",
    "Smart Blinds",
    "Custom Closets",
    "Murphy Bed",
    "Vertical Garden",
    "Pocket Doors",
    "Reclaimed Wood Features",
    "Seamless Glass Shower",
    "Concrete Countertops",
    "Wine Racks",
    "Expansive Walk-in Closet",
    "Decorative Walls",
    "Accent Lighting",
    "Vaulted Ceilings",
    "Mudroom with Storage",
    "Laundry Chute",
    "Art Studio",
    "Game Room",
    "Outdoor Lounge",
    "Private Balcony",
    "Frosted Glass Windows",
    "Sliding Glass Doors",
    "Adjustable Shelving",
    "Chandelier Lighting",
    "Rustic Features",
    "Roller Shades",
    "Recessed Shelving",
    "Built-in Wardrobe",
    "Guest Suite",
    "Wet Bar with Refrigerator",
    "Dual Master Suites",
    "Dual Sinks",
    "Barbecue Grill",
    "Smart Doorbell",
    "Invisible Speakers",
    "Frosted Glass Shower Doors",
    "Large Entryway",
    "Home Spa",
    "Walkable Garden Path",
    "Indoor-Outdoor Flow",
    "Wine Display",
    "Exercise Room",
    "Sunroom",
    "Secret Room",
    "Basement Bar",
    "Private Pathway",
    "Secret Garden",
    "Built-in BBQ",
    "Quiet Location",
    "Airlock Entry",
    "Solar-Powered Appliances",
    "Double Ovens",
    "Caterer's Kitchen",
    "Customized Flooring",
    "Quartz Countertops",
    "Smart Mirror",
    "Hidden Cabinet",
    "Smart Lighting Zones",
    "Fire Escape Ladder",
    "Butler's Pantry",
    "Conservatory",
    "Freestanding Bathtub",
    "Modern Fixtures",
    "Outdoor Entertainment Area",
    "Detached Garage",
    "Eco-Friendly Insulation",
    "Floor-to-Ceiling Windows",
    "Glass Walls",
    "Stained Glass Windows",
    "Vaulted Roof",
    "Open Beam Ceiling",
    "Built-in Vacuum",
    "Hydronic Radiant Heating",
    "Home Brewing Station",
    "Tech-ready Office",
    "Energy-efficient Windows",
    "Walk-in Closet with Mirror",
    "Outdoor Dining Space",
    "Natural Wood Floors",
    "Smart AC Unit",
    "Multiple Entry Points",
    "High-end Appliances",
    "Pre-fabricated Fireplace",
    "Full-length Mirrors",
    "Billiard Room",
    "Study Nook",
    "Storage for Seasonal Items",
    "Treehouse",
    "Tennis Court",
    "Fish Pond",
    "Garden Lights",
    "Mudroom Sink",
    "Reclaimed Wood Deck",
    "Movable Kitchen Island",
    "Built-in Desk in Kitchen",
    "Hidden Pantry",
    "Rustic Wood Beams",
    "Home Theater System",
    "Daylight Basement",
    "Oversized Windows",
    "Floating Stairs",
    "Dual Zone Climate Control",
    "Beach Access",
    "Private Elevator",
    "Custom Wall Colors",
    "Outdoor Kitchen with Sink",
    "Deep Soaking Tub",
    "Waterfront Access",
    "Private Dock",
    "High-End Water Fixtures",
    "Custom Staircase",
    "Stone Fireplace",
    "Sky Lounge",
    "Wood-burning Stove",
    "Privacy Screens",
    "Sound Insulation",
    "Indoor Water Feature",
    "Formal Dining Room",
    "Cabana",
    "Sustainable Materials",
    "Customized Hardware",
    "Contemporary Design",
    "Eco-friendly Roof",
    "Living Wall",
    "Aluminum Framed Windows",
    "Sleek Kitchen Design",
    "Smart Refrigerator",
    "Furnished Patio",
    "Portable Dishwasher",
    "Roof Overhang",
    "Designated Home Office Area",
    "Mudroom with Bench",
    "Floating Vanity",
    "Adjustable Lighting",
    "Indoor Greenery",
    "Retractable Screen",
    "Architectural Detailing",
    "Suspended Lighting",
    "Smart Bathroom Mirror",
    "Professional-grade Appliances",
    "Disappearing Screen Doors",
    "Fireplace in Living Room",
    "Hardwood Paneling",
    "Built-in Coffee Maker",
    "Artistic Touches",
    "Wrought Iron Railings",
    "Custom Wall Paper",
    "In-home Library",
    "Under-floor Heating",
    "Private Courtyard",
    "Rain Garden",
    "Heated Garage",
    "High-performance HVAC",
    "Private Study",
    "Upgraded Fixtures",
    "Panoramic Views",
    "Glass Balustrade",
    "Home Greenhouse",
    "Indoor Bar",
    "Exquisite Tile Work",
    "Walking Trails",
    "Upgraded Windows",
    "Central Audio System",
    "In-floor Heating",
    "Zero Energy Building",
    "Bamboo Flooring",
    "Private Garden Entrance",
    "Fully Landscaped Garden",
    "Garden Path Lights",
    "Under-cabinet Wine Cooler",
    "Energy Star Appliances",
    "Decorative Pool Tiles",
    "Sculptural Architecture",
    "Cozy Fireplace",
    "Four-poster Bed",
    "Bedroom with a View",
    "Geothermal Heating",
    "Sustainable Decking",
    "Energy-efficient Lighting",
    "High-quality Soundproofing",
    "Concrete Flooring",
    "Handmade Tiles",
    "Luxury Fixtures",
    "Natural Stone Flooring",
    "Walk-in Closet with Lighting",
    "Chic Lighting Fixtures",
    "Chic Design",
    "Garage Loft",
    "Vaulted Living Room",
    "Advanced Irrigation System",
    "Tranquil Yard",
    "Decorative Ceiling",
    "Heated Outdoor Space",
    "Exotic Wood Flooring",
    "Smart Front Door",
    "Flexible Layout",
    "Pocket Window Blinds",
    "Indoor/Outdoor Living Space",
    "Industrial Style",
    "Smart Kitchen Appliances",
    "Custom-designed Furniture",
    "Indoor Garden",
    "Outdoor Entertainment System",
    "Glass Railings",
    "Oversized Tub",
    "Unique Tile Design",
    "Fireplace in Master Bedroom",
    "Designer Bathroom Fixtures",
    "French Windows",
    "Under-cabinet Storage",
    "Storage Space for Tools",
    "Custom Cabinet Design",
    "Fitted Wardrobe",
    "Panoramic Balcony",
    "Multi-functional Living Area",
    "Outdoor Yoga Deck",
    "Sustainable Landscaping",
    "Walk-in Closet with Dressing Area",
    "Electric Heating",
    "Custom Backsplash",
    "High-tech Home Automation",
    "Soundproof Walls",
    "Wine Tasting Room",
    "Private Beach",
    "Gas Log Fireplace",
    "Outdoor Bar",
    "Water Features",
    "Low-maintenance Garden",
    "Fireplace with Marble Surround",
    "Energy Efficient Doors",
    "Pool Lounge Area",
    "Full Kitchen in Garage",
    "Two-car Garage",
    "Customized Entryway",
    "Built-in Fire Pit",
    "Built-in Refrigerator",
    "Outdoor Shower Area",
    "Patio Heater",
    "Stacked Stone Fireplace",
    "Fireplace in Entryway",
    "Private Poolside",
    "Glass Shower Doors",
    "Heated Towel Racks",
    "Decorative Floor Tiles",
    "Home Lighting System",
    "Recessed Pool Lighting",
    "Large Yard",
    "Covered Porch",
    "Well-manicured Lawn",
    "Spacious Living Area",
    "Modern Architecture",
    "Sleek Cabinetry",
    "Luxury Bathroom",
    "Rain Shower Head",
    "Curb Appeal",
    "Meditation Room",
    "Upgraded Appliances",
    "Compact Appliances",
    "Garage Storage",
    "Under-cabinet Lighting",
    "Exposed Concrete Walls",
    "Gourmet Kitchen",
    "Private Pool",
    "Outdoor Fireplace",
    "Masonry Walls",
    "Barbecue Pit",
    "Zen Garden",
    "Wall-mounted TV",
    "Extra-wide Hallways",
    "Sound System throughout Home",
    "Landscape Lighting",
    "Meditation Garden",
    "Tile Pool Deck",
    "Completely Fenced Yard",
    "Private Driveway",
    "Landscaped Pathways",
    "Artificial Turf",
    "Glass Floor Panels",
    "Open-concept Layout",
    "Modern Floor Plan",
    "Sunlit Rooms",
    "Bright Color Scheme",
    "Sustainable Flooring",
    "Recycled Glass Backsplash",
    "Alfresco Dining",
    "Built-in Storage Solutions",
    "Breezeway",
    "Impressive Entryway",
    "Hidden Lighting",
    "Sculptural Stairs",
    "Panoramic Roof",
    "Great Room",
    "Exposed Brick Walls",
    "Faux Beam Ceiling",
    "Gated Property",
    "Tiled Patio",
    "Detached Guest House",
    "Climate-controlled Wine Cellar",
    "Ornate Woodwork",
    "Floating Bed",
    "Walled Courtyard",
    "Green Roof",
    "Flexible Workspace",
    "Private Courtyard Garden",
    "Mosaic Tile Floor",
    "Heated Driveway",
    "Four Seasons Room",
    "Zero Maintenance Yard",
    "Oversized Pool Deck",
    "Leed Certified Building",
    "Architectural Feature Walls",
    "French Doors to Patio",
    "Outdoor Pool with Jacuzzi",
    "Recessed Pool Lights",
    "Pond",
    "Energy-efficient Roof",
    "Marble Flooring",
    "Glass-front Cabinets",
    "Exquisite Landscaping",
    "Natural Stone Decking",
    "Contemporary Architecture",
    "Decorative Ironwork",
    "Elevated Living Spaces",
    "Tree-lined Driveway",
    "Smart Thermostat System",
    "Swimming Pool with Waterfall",
    "Built-in Coffee Machine",
    "Private Wine Cellar",
    "Handcrafted Wood Flooring",
    "Glass Garage Doors",
    "Outdoor Yoga Space",
    "Smart Security",
    "Chic Urban Design",
    "Spa Room",
    "Covered Outdoor Lounge",
    "Retractable Windows",
    "Luxury Kitchen",
    "Walk-in Closet with Mirror",
    "Jetted Tub",
    "Fountain",
    "Detached Garage with Loft",
    "Open Kitchen Shelving",
    "Outdoor Lounge with Firepit",
    "Family Room",
    "Outdoor Spa",
    "Spa-like Bathroom",
    "Vaulted Ceiling in Living Room",
    "Luxury Backsplash",
    "Modern Barn Door",
    "Extra-large Windows",
    "Reclaimed Hardwood Floors",
    "Custom Cabinet Hardware",
    "Under-cabinet Drawers",
    "Kitchen Island with Storage",
    "Luxury Light Fixtures",
    "Wooden Paneling",
    "In-house Garden",
    "Smart Fridge with WiFi",
    "Private Hot Tub",
    "Spa Pool",
    "Kitchen with Pantry",
    "Home Automation System",
    "Wood-burning Stove in Living Room",
    "Private Hot Tub in Yard",
    "Energy-efficient Walls",
    "Stylish Fixtures",
    "Dual Shower Head",
    "Smart Home Features",
    "Open Plan Kitchen",
    "Modern Sliding Doors",
    "Solar Powered Lights",
    "Private Terrace",
    "Dual-glazed Windows",
    "Quartz Backsplash",
    "Dual-flush Toilet",
    "Zero Energy Home",
    "Upgraded Plumbing",
    "In-ground Pool",
    "Custom Lighting Design",
    "Expansive Outdoor Deck",
    "Wooden Flooring",
    "Luxurious Entryway",
    "Gorgeous Living Area",
    "Handmade Furniture",
    "Multi-functional Spaces",
    "Sustainable Architecture",
    "Eco-friendly Windows",
    "Quartz Counter",
    "Walk-in Closet with Island",
    "Backyard Water Feature",
    "Smart Home System",
    "Heated Floors in Bathroom",
    "Bespoke Bathroom Fixtures",
    "Eco Home",
    "Smart Window Blinds",
    "Oversized Walk-in Closet",
    "Marble Backsplash in Kitchen",
    "Exposed Concrete Floor",
    "Private Garden with Trees",
    "Customized Entry Door",
    "Soundproofed Bedrooms",
    "Free-standing Bath",
    "Energy-efficient Plumbing",
    "Granite Wall Finish",
    "Custom Pool Design",
    "Zoned Air Conditioning",
    "Exclusive Gated Community",
    "Air-tight Construction",
    "Stainless Steel Finishes",
    "Rainwater Collection System",
    "Interior Waterfall Feature",
    "Personalized Closet",
    "High-efficiency Appliances",
    "Luxury Bedroom Design",
    "Sustainable Wall Insulation",
    "High-tech Lighting System",
    "Flexible Floor Plan",
    "Private Elevator in Home",
    "Modern Fire Pit",
    "Private Courtyard Garden",
    "Premium Flooring Options",
    "Architectural Lighting",
    "Marble Tiling",
    "Mature Trees in Yard",
    "Well-designed Garage Space",
    "Breezy Living Spaces",
    "Walkable Streets",
    "Large Windows",
    "Spa-influenced Design",
    "Unique Ceiling Design",
    "Swimming Pool with Beach Entry",
    "Customized Pool Tiles",
    "Tropical Garden",
    "Customized Windows",
    "Outdoor Living Area",
    "Exquisite Pool Design",
    "Heated Pool Area",
    "Luxury Home Automation"
  ]
  