package utils

// contradictionsKeywords maps negated property features to their positive counterparts.
var ContradictionsKeywords = map[string]string{
	"no swimming pool":                          "has swimming pool",
	"no garden":                                 "has garden",
	"no garage":                                 "has garage",
	"no balcony":                                "has balcony",
	"no fireplace":                              "has fireplace",
	"no gym":                                    "has gym",
	"no parking":                                "has parking",
	"no sauna":                                  "has sauna",
	"no washer/dryer":                           "has washer/dryer",
	"no air conditioning":                       "has air conditioning",
	"no dishwasher":                             "has dishwasher",
	"no furnished":                              "is furnished",
	"no security system":                        "has security system",
	"no walk-in closet":                         "has walk-in closet",
	"not pet friendly":                          "is pet friendly",
	"no elevator":                               "has elevator",
	"no smart home":                             "is a smart home",
	"no rooftop terrace":                        "has rooftop terrace",
	"no basement":                               "has basement",
	"no solar panels":                           "has solar panels",
	"no garden shed":                            "has garden shed",
	"no home office":                            "has home office",
	"no playground":                             "has playground",
	"no bicycle storage":                        "has bicycle storage",
	"no security gate":                          "has security gate",
	"no fenced yard":                            "has fenced yard",
	"not wheelchair accessible":                 "is wheelchair accessible",
	"no electric car charging station":          "has electric car charging station",
	"no jacuzzi":                                "has jacuzzi",
	"no double glazed windows":                  "has double glazed windows",
	"no high ceilings":                          "has high ceilings",
	"no ceiling fans":                           "has ceiling fans",
	"no hardwood floors":                        "has hardwood floors",
	"no granite countertops":                    "has granite countertops",
	"no marble floors":                          "has marble floors",
	"no custom cabinetry":                       "has custom cabinetry",
	"no home theater":                           "has home theater",
	"no walk-in pantry":                         "has walk-in pantry",
	"no open floor plan":                        "has open floor plan",
	"no large windows":                          "has large windows",
	"no mudroom":                                "has mudroom",
	"no recessed lighting":                      "has recessed lighting",
	"no central heating":                        "has central heating",
	"no central cooling":                        "has central cooling",
	"no high-speed internet":                    "has high-speed internet",
	"not cable ready":                           "is cable ready",
	"no wine cellar":                            "has wine cellar",
	"no hot tub":                                "has hot tub",
	"no gated community":                        "is in a gated community",
	"no swimming pool heater":                   "has swimming pool heater",
	"no fire pit":                               "has fire pit",
	"no laundry room":                           "has laundry room",
	"no guest house":                            "has guest house",
	"no private garden":                         "has private garden",
	"no home gym":                               "has home gym",
	"no barbecue area":                          "has barbecue area",
	"no sports court":                           "has sports court",
	"not walkable neighborhood":                 "is in a walkable neighborhood",
	"no views of the city":                      "has views of the city",
	"no city lights":                            "has city lights",
	"no lake view":                              "has lake view",
	"no mountain view":                          "has mountain view",
	"no ocean view":                             "has ocean view",
	"no backyard patio":                         "has backyard patio",
	"no covered parking":                        "has covered parking",
	"no storage shed":                           "has storage shed",
	"no workshop":                               "has workshop",
	"no attic":                                  "has attic",
	"no natural stone counters":                 "has natural stone counters",
	"no marble countertops":                     "has marble countertops",
	"no walk-in shower":                         "has walk-in shower",
	"no double vanity":                          "has double vanity",
	"no security cameras":                       "has security cameras",
	"no cctv system":                            "has cctv system",
	"no smart thermostat":                       "has smart thermostat",
	"no smart lights":                           "has smart lights",
	"no smart locks":                            "has smart locks",
	"no surround sound system":                  "has surround sound system",
	"no custom lighting":                        "has custom lighting",
	"no soundproofing":                          "has soundproofing",
	"no rain shower":                            "has rain shower",
	"no home automation":                        "has home automation",
	"no heat recovery ventilation":              "has heat recovery ventilation",
	"no water filtration system":                "has water filtration system",
	"no smart refrigerator":                     "has smart refrigerator",
	"no dishwasher with stainless steel finish": "has dishwasher with stainless steel finish",
	"no heated floors":                          "has heated floors",
	"no granite island":                         "has granite island",
	"no lush landscaping":                       "has lush landscaping",
	"no outdoor kitchen":                        "has outdoor kitchen",
	"no wine fridge":                            "has wine fridge",
	"no roof deck":                              "has roof deck",
	"no home library":                           "has home library",
	"no outdoor fireplace":                      "has outdoor fireplace",
	"no multi-zone hvac":                        "has multi-zone hvac",
	"no panoramic windows":                      "has panoramic windows",
	"no loft":                                   "has loft",
	"no garage door opener":                     "has garage door opener",
	"no wooden blinds":                          "has wooden blinds",
	"no skylights":                              "has skylights",
	"no built-in speakers":                      "has built-in speakers",
	"no pre-wired for sound":                    "is pre-wired for sound",
	"no french doors":                           "has french doors",
	"no alcove":                                 "has alcove",
	"no linen closet":                           "has linen closet",
	"no mudroom bench":                          "has mudroom bench",
	"no open shelving":                          "has open shelving",
	"no under-cabinet lighting":                 "has under-cabinet lighting",
	"no wet bar":                                "has wet bar",
	"no in-wall safe":                           "has in-wall safe",
	"no central vacuum system":                  "has central vacuum system",
	"no water softener":                         "has water softener",
	"no solar water heater":                     "has solar water heater",
	"no fireplace with mantel":                  "has fireplace with mantel",
}
